name: test-app

services:
  test-app-redis:
    container_name: 'test-app-redis'
    image: redis:latest
    restart: unless-stopped
  test-app-postgres:
    container_name: 'test-app-postgres'
    image: postgres:latest
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: